project:
  type: website

website:
  title: "some slide decks"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
  



    
#beige
#blood
#dark
#default
#league
#moon
#night
#serif
#simple
#sky
#solarized


